name: Deploy portal to Alicloud OSS
on:
  push:
    branches:
      - stg
      - prod

env:
  BUCKET: ${{ vars.OSS_BUCKET }}
  ENDPOINT: ${{ vars.OSS_ENDPOINT }}
  ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
  ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VUE_APP_NAME: ${{ vars.APP_NAME }}
      VUE_APP_API_BASE_URL: ${{ vars.API_BASE_URL }}
      VUE_APP_AUTH_STORE_PREFIX: ${{ vars.AUTH_STORE_PREFIX }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: 20
      - run: npm ci
      - run: apk update && apk --no-cache add git
      - run: git config --global credential.helper store
      - run: echo "https://${{ vars.GITLAB_USER_NAME }}:${{ secrets.GITLAB_PERSONAL_TOKEN }}@gitlab.com" > ~/.git-credentials
      - run: npm run generate


      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: oss
          region: ${{ secrets.OSS_ACCESS_KEY_ID }}
          bucket: saltbo-blog
          exclude: .cache,test
          dist: dist
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.OSS_ACCESS_KEY_ID }}
          UPTOC_UPLOADER_SK: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
